//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC_MoodLog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POC_MoodLog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a+
        ///abound
        ///abounds
        ///abundance
        ///abundant
        ///accessable
        ///accessible
        ///acclaim
        ///acclaimed
        ///acclamation
        ///accolade
        ///accolades
        ///accommodative
        ///accomodative
        ///accomplish
        ///accomplished
        ///accomplishment
        ///accomplishments
        ///accurate
        ///accurately
        ///achievable
        ///achievement
        ///achievements
        ///achievible
        ///acumen
        ///adaptable
        ///adaptive
        ///adequate
        ///adjustable
        ///admirable
        ///admirably
        ///admiration
        ///admire
        ///admirer
        ///admiring
        ///admiringly
        ///adorable
        ///adore
        ///adored
        ///adorer
        ///adoring
        ///adoringly
        ///adroit
        ///adroitly
        ///adulate
        ///adulation
        ///adulatory
        ///advan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bow_algorithm_reference {
            get {
                return ResourceManager.GetString("bow_algorithm_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :)
        ///:(.
        /// </summary>
        internal static string emoticons {
            get {
                return ResourceManager.GetString("emoticons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and
        ///best
        ///can
        ///cannot
        ///can&apos;t
        ///could
        ///couldn&apos;t
        ///did
        ///didn&apos;t
        ///do
        ///does
        ///doesn&apos;t
        ///don&apos;t
        ///either
        ///every
        ///for
        ///from
        ///have
        ///haven&apos;t
        ///he&apos;s
        ///is
        ///isn&apos;t
        ///its
        ///just
        ///like
        ///lots
        ///many
        ///maybe
        ///might
        ///more
        ///must
        ///my
        ///never
        ///no
        ///none
        ///not
        ///nothing
        ///of
        ///on
        ///once
        ///one
        ///only
        ///or
        ///overly
        ///perfectly
        ///perhaps
        ///probably
        ///seemed
        ///seems
        ///she&apos;s
        ///should
        ///simply
        ///so
        ///some
        ///somehow
        ///something
        ///soon
        ///start
        ///takes
        ///tell
        ///thank
        ///that&apos;s
        ///the
        ///their
        ///them
        ///then
        ///there
        ///there&apos;s
        ///they
        ///they&apos;re
        ///this
        ///those
        ///to
        ///too
        ///totally
        ///tried
        ///truly
        ///t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ngrams1 {
            get {
                return ResourceManager.GetString("ngrams1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am very happy. I am happy. I am very gwapo. :) #LoveWins.
        /// </summary>
        internal static string SampleIn {
            get {
                return ResourceManager.GetString("SampleIn", resourceCulture);
            }
        }
    }
}
