//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC_MoodLog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POC_MoodLog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abduction
        ///abortion
        ///absurd
        ///abundance
        ///abuse
        ///acceptance
        ///accident
        ///ace
        ///ache
        ///achievement
        ///activate
        ///addict
        ///addicted
        ///admired
        ///adorable
        ///adult
        ///advantage
        ///adventure
        ///affection
        ///afraid
        ///aggressive
        ///agility
        ///agony
        ///agreement
        ///air
        ///alcoholic
        ///alert
        ///alien
        ///alimony
        ///alive
        ///allergy
        ///alley
        ///alone
        ///aloof
        ///ambition
        ///ambulance
        ///angel
        ///anger
        ///angry
        ///anguished
        ///ankle
        ///annoy
        ///answer
        ///anxious
        ///applause
        ///appliance
        ///arm
        ///army
        ///aroused
        ///arrogant
        ///art
        ///assassin
        ///assault
        ///astonished
        ///astronaut
        ///athletics
        ///autumn
        ///avalanch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bow_algorithm_reference {
            get {
                return ResourceManager.GetString("bow_algorithm_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :)
        ///:-)
        ///:]
        ///=)
        ///:D
        ///:smiling_face:
        ///^^
        ///:smiling_face_with_smiling_eyes:
        ///:smiling_face_with_heart_shaped_eyes:
        ///:face_with_tears_of_joy:
        ///:smiling_face_with_open_mouth:
        ///:grinning_face_with_smiling_eyes:
        ///O:)
        ///O:-)
        ///:smiling_face_with_halo:
        ///&lt;3
        ///:heavy_black_heart:
        ///;)
        ///;-)
        ///:winking_face:
        ///:face_with_open_mouth:
        ///:astonished_face:
        ///:hushed_face:
        ///:face_screaming_in_fear:
        ///:(
        ///:-(
        ///:sad_face:
        ///:pensive_face:
        ///:disappointed_face:
        ///T_T
        ///:loudly_crying_face:
        ///:’(
        ///:crying_face:
        ///:worried_face:
        ///&lt;/3
        ///:broken_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emoticons {
            get {
                return ResourceManager.GetString("emoticons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and
        ///best
        ///can
        ///cannot
        ///can&apos;t
        ///could
        ///couldn&apos;t
        ///did
        ///didn&apos;t
        ///do
        ///does
        ///doesn&apos;t
        ///don&apos;t
        ///either
        ///every
        ///for
        ///from
        ///have
        ///haven&apos;t
        ///he&apos;s
        ///is
        ///isn&apos;t
        ///its
        ///just
        ///like
        ///lots
        ///many
        ///maybe
        ///might
        ///more
        ///must
        ///my
        ///never
        ///no
        ///none
        ///not
        ///nothing
        ///of
        ///on
        ///once
        ///one
        ///only
        ///or
        ///overly
        ///perfectly
        ///perhaps
        ///probably
        ///seemed
        ///seems
        ///she&apos;s
        ///should
        ///simply
        ///so
        ///some
        ///somehow
        ///something
        ///soon
        ///start
        ///takes
        ///tell
        ///thank
        ///that&apos;s
        ///the
        ///their
        ///them
        ///then
        ///there
        ///there&apos;s
        ///they
        ///they&apos;re
        ///this
        ///those
        ///to
        ///too
        ///totally
        ///tried
        ///truly
        ///t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ngrams1 {
            get {
                return ResourceManager.GetString("ngrams1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aback	anger	 
        ///aback	disgust	 
        ///aback	fear	 
        ///aback	joy	 
        ///aback	sadness	 
        ///aback	surprise	 
        ///abacus	anger	 
        ///abacus	disgust	 
        ///abacus	fear	 
        ///abacus	joy	 
        ///abacus	sadness	 
        ///abacus	surprise	 
        ///abandon	anger	 
        ///abandon	disgust	 
        ///abandon	fear	  
        ///abandon	joy	 
        ///abandon	sadness	  
        ///abandon	surprise	 
        ///abandoned	anger	  
        ///abandoned	disgust	 
        ///abandoned	fear	  
        ///abandoned	joy	 
        ///abandoned	sadness	  
        ///abandoned	surprise	 
        ///abandonment	anger	  
        ///abandonment	disgust	 
        ///abandonment	fear	  
        ///abandonment	joy	 
        ///abandonment	sadness	  
        ///abandonme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NRC_emotion {
            get {
                return ResourceManager.GetString("NRC_emotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and,+
        ///best,+
        ///can,+
        ///cannot,-
        ///can&apos;t,-
        ///could,+
        ///couldn&apos;t,-
        ///did,+
        ///didn&apos;t,-
        ///do,+
        ///does,+
        ///doesn&apos;t,-
        ///don&apos;t,-
        ///either,+
        ///every,+
        ///more,+
        ///must,+
        ///never,-
        ///no,-
        ///not,-
        ///overly,+
        ///perfectly,+
        ///simply,+
        ///so,+
        ///too,+
        ///totally,+
        ///truly,+
        ///very,+
        ///was,-.
        /// </summary>
        internal static string PrepRef {
            get {
                return ResourceManager.GetString("PrepRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am happy to know that I made the MSP Program though it was very hard during the interview, I think I did well..
        /// </summary>
        internal static string SampleIn {
            get {
                return ResourceManager.GetString("SampleIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import sys
        ///sys.path.append(&quot;C:\python27\lib&quot;)
        ///from wordsegment import segment
        ///def simpleFunc(x):
        ///    return str(segment(x))
        ///simpleFunc(x).
        /// </summary>
        internal static string wordseg {
            get {
                return ResourceManager.GetString("wordseg", resourceCulture);
            }
        }
    }
}
