//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_moodlog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wpf_moodlog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abduction,2.76,5.53
        ///abortion,3.5,5.39
        ///absurd,4.26,4.36
        ///abundance,6.59,5.51
        ///abuse,1.8,6.83
        ///acceptance,7.98,5.4
        ///accident,2.05,6.26
        ///ace,6.88,5.5
        ///ache,2.46,5
        ///achievement,7.89,5.53
        ///activate,5.46,4.86
        ///addict,2.48,5.66
        ///addicted,2.51,4.81
        ///admired,7.74,6.11
        ///adorable,7.81,5.12
        ///adult,6.49,4.76
        ///advantage,6.95,4.76
        ///adventure,7.6,6.98
        ///affection,8.39,6.21
        ///afraid,2,6.67
        ///aggressive,5.1,5.83
        ///agility,6.46,4.85
        ///agony,2.43,6.06
        ///agreement,7.08,5.02
        ///air,6.34,4.12
        ///alcoholic,2.84,5.69
        ///alert,6.2,6.85
        ///alien [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string anewReference {
            get {
                return ResourceManager.GetString("anewReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abduction
        ///abortion
        ///absurd
        ///abundance
        ///abuse
        ///acceptance
        ///accident
        ///ace
        ///achievement
        ///activate
        ///addict
        ///addicted
        ///admired
        ///adorable
        ///adult
        ///advantage
        ///adventure
        ///affection
        ///afraid
        ///aggressive
        ///agility
        ///agony
        ///agreement
        ///air
        ///alcoholic
        ///alert
        ///alien
        ///alimony
        ///alive
        ///allergy
        ///alley
        ///alone
        ///aloof
        ///ambition
        ///ambulance
        ///angel
        ///anger
        ///angry
        ///anguished
        ///ankle
        ///annoy
        ///answer
        ///anxious
        ///applause
        ///appliance
        ///arm
        ///army
        ///aroused
        ///arrogant
        ///art
        ///assassin
        ///assault
        ///astonished
        ///astronaut
        ///athletics
        ///autumn
        ///avalanche
        ///ave [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bow_algorithm_reference {
            get {
                return ResourceManager.GetString("bow_algorithm_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :)
        ///:-)
        ///:]
        ///=)
        ///:D
        ///:smiling_face:
        ///^^
        ///:smiling_face_with_smiling_eyes:
        ///:smiling_face_with_heart_shaped_eyes:
        ///:face_with_tears_of_joy:
        ///:smiling_face_with_open_mouth:
        ///:grinning_face_with_smiling_eyes:
        ///O:)
        ///O:-)
        ///:smiling_face_with_halo:
        ///&lt;3
        ///:heavy_black_heart:
        ///;)
        ///;-)
        ///:winking_face:
        ///:face_with_open_mouth:
        ///:astonished_face:
        ///:hushed_face:
        ///:face_screaming_in_fear:
        ///:(
        ///:-(
        ///:sad_face:
        ///:pensive_face:
        ///:disappointed_face:
        ///T_T
        ///TT
        ///:loudly_crying_face:
        ///:’(
        ///:crying_face:
        ///:worried_face:
        ///&lt;/3
        ///:bro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emoticons {
            get {
                return ResourceManager.GetString("emoticons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to best 
        ///cannot  
        ///can&apos;t  
        ///couldn&apos;t  
        ///didn&apos;t  
        ///doesn&apos;t  
        ///don&apos;t  
        ///more  
        ///most 
        ///never  
        ///no  
        ///not  
        ///overly 
        ///perfectly 
        ///so 
        ///too 
        ///totally 
        ///truly
        ///very.
        /// </summary>
        internal static string ngrams1 {
            get {
                return ResourceManager.GetString("ngrams1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abduction,2.76,5.53
        ///abortion,3.5,5.39
        ///absurd,4.26,4.36
        ///abundance,6.59,5.51
        ///abuse,1.8,6.83
        ///acceptance,7.98,5.4
        ///accident,2.05,6.26
        ///ace,6.88,5.5
        ///ache,2.46,5
        ///achievement,7.89,5.53
        ///activate,5.46,4.86
        ///addict,2.48,5.66
        ///addicted,2.51,4.81
        ///admired,7.74,6.11
        ///adorable,7.81,5.12
        ///adult,6.49,4.76
        ///advantage,6.95,4.76
        ///adventure,7.6,6.98
        ///affection,8.39,6.21
        ///afraid,2,6.67
        ///aggressive,5.1,5.83
        ///agility,6.46,4.85
        ///agony,2.43,6.06
        ///agreement,7.08,5.02
        ///air,6.34,4.12
        ///alcoholic,2.84,5.69
        ///alert,6.2,6.85
        ///alien [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NRC_emotion_lexicon_wordlevel_alphabetized_v0_92__1_ {
            get {
                return ResourceManager.GetString("NRC_emotion_lexicon_wordlevel_alphabetized_v0_92__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to best,+,1
        ///cannot,-,1
        ///can&apos;t,-,1
        ///couldn&apos;t,-,1
        ///didn&apos;t,-,1
        ///doesn&apos;t,-,1
        ///don&apos;t,-,1
        ///more,+,.5
        ///most,+,1
        ///never,-,1
        ///no,-,1
        ///not,-,1
        ///overly,+,1
        ///perfectly,+,1
        ///so,+,1
        ///too,+,1
        ///totally,+,1
        ///truly,+,1
        ///very,+,1.
        /// </summary>
        internal static string PrepRef {
            get {
                return ResourceManager.GetString("PrepRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///!
        ///?
        ///;
        ///.
        /// </summary>
        internal static string punctuations {
            get {
                return ResourceManager.GetString("punctuations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] python {
            get {
                object obj = ResourceManager.GetObject("python", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am very Happy.
        /// </summary>
        internal static string SampleIn {
            get {
                return ResourceManager.GetString("SampleIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //happy-sad-fear-anger-surprise-disgust//
        ///a+
        ///abound
        ///abounds
        ///abundance
        ///abundant
        ///accessable
        ///accessible
        ///acclaim
        ///acclaimed
        ///acclamation
        ///accolade
        ///accolades
        ///accommodative
        ///accomodative
        ///accomplish
        ///accomplished
        ///accomplishment
        ///accomplishments
        ///accurate
        ///accurately
        ///achievable
        ///achievement
        ///achievements
        ///achievible
        ///acumen
        ///adaptable
        ///adaptive
        ///adequate
        ///adjustable
        ///admirable
        ///admirably
        ///admiration
        ///admire
        ///admirer
        ///admiring
        ///admiringly
        ///adorable
        ///adore
        ///adored
        ///adorer
        ///adoring
        ///adoringly
        ///adroit
        ///adr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wordbank {
            get {
                return ResourceManager.GetString("wordbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import sys
        ///sys.path.append(&quot;C:\Python27\Lib&quot;)
        ///from wordsegment import segment
        ///def simpleFunc(x):
        ///    return str(segment(x))
        ///simpleFunc(x).
        /// </summary>
        internal static string wordseg {
            get {
                return ResourceManager.GetString("wordseg", resourceCulture);
            }
        }
    }
}
